name: workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Check editorconfig
        run: editorconfig-checker
      - name: Check gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then echo "Please format the code."; exit 1; fi
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  go-report-card:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger go report card
        uses: creekorful/goreportcard-action@v1.0
