name: workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Check editorconfig
        run: editorconfig-checker
      - name: Check gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then echo "Please format the code."; exit 1; fi
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  go-report-card:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger go report card
        uses: creekorful/goreportcard-action@v1.0
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push t4k-account-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-account-service/Dockerfile
          push: true
          tags: huaouo/t4k-account-service:latest
      - name: Build and push t4k-rdbms-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-rdbms-service/Dockerfile
          push: true
          tags: huaouo/t4k-rdbms-service:latest
      - name: Build and push t4k-object-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-object-service/Dockerfile
          push: true
          tags: huaouo/t4k-object-service:latest
      - name: Build and push t4k-mq-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-mq-service/Dockerfile
          push: true
          tags: huaouo/t4k-mq-service:latest
      - name: Build and push t4k-cover-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-cover-service/Dockerfile
          push: true
          tags: huaouo/t4k-cover-service:latest
      - name: Build and push t4k-video-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: t4k-video-service/Dockerfile
          push: true
          tags: huaouo/t4k-video-service:latest
